ELL_DEFBUILTIN(sym)
ELL_DEFBUILTIN(str)
ELL_DEFBUILTIN(clo)
ELL_DEFBUILTIN(lst)
ELL_DEFBUILTIN(boolean)
ELL_DEFBUILTIN(unspecified)
ELL_DEFBUILTIN(unbound)

ELL_DEFBUILTIN(list_range)

ELL_DEFBUILTIN(stx_sym)
ELL_DEFBUILTIN(stx_str)
ELL_DEFBUILTIN(stx_lst)
