/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 21

void
ell_parser_add_sym(char *chars);
void
ell_parser_add_str(char *chars);
void
ell_parser_add_num(char *chars);
void
ell_parser_push();
void
ell_parser_pop();
void
ell_parser_push_quote();
void
ell_parser_push_syntax();
void
ell_parser_push_quasisyntax();
void
ell_parser_push_unsyntax();
void
ell_parser_push_unsyntax_splicing();

#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_eol(); /* 21 */
YY_RULE(int) yy_spc_char(); /* 20 */
YY_RULE(int) yy_contents(); /* 19 */
YY_RULE(int) yy_CLOSE(); /* 18 */
YY_RULE(int) yy_OPEN(); /* 17 */
YY_RULE(int) yy_sym_char(); /* 16 */
YY_RULE(int) yy_doc(); /* 15 */
YY_RULE(int) yy_lst(); /* 14 */
YY_RULE(int) yy_sym(); /* 13 */
YY_RULE(int) yy_num(); /* 12 */
YY_RULE(int) yy_str(); /* 11 */
YY_RULE(int) yy_unsyntax_splicing(); /* 10 */
YY_RULE(int) yy_unsyntax(); /* 9 */
YY_RULE(int) yy_quasisyntax(); /* 8 */
YY_RULE(int) yy_syntax(); /* 7 */
YY_RULE(int) yy_quote(); /* 6 */
YY_RULE(int) yy_expr(); /* 5 */
YY_RULE(int) yy_spc(); /* 4 */
YY_RULE(int) yy_eof(); /* 3 */
YY_RULE(int) yy_exprs(); /* 2 */
YY_RULE(int) yy_unit(); /* 1 */

YY_ACTION(void) yy_1_contents(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_contents\n"));
   ell_parser_add_str(yytext); ;
}
YY_ACTION(void) yy_2_doc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_doc\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_doc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_doc\n"));
   ell_parser_push(); ;
}
YY_ACTION(void) yy_2_unsyntax_splicing(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_unsyntax_splicing\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_unsyntax_splicing(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unsyntax_splicing\n"));
   ell_parser_push_unsyntax_splicing(); ;
}
YY_ACTION(void) yy_2_unsyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_unsyntax\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_unsyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unsyntax\n"));
   ell_parser_push_unsyntax(); ;
}
YY_ACTION(void) yy_2_quasisyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_quasisyntax\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_quasisyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_quasisyntax\n"));
   ell_parser_push_quasisyntax(); ;
}
YY_ACTION(void) yy_2_syntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_syntax\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_syntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_syntax\n"));
   ell_parser_push_syntax(); ;
}
YY_ACTION(void) yy_2_quote(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_quote\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_quote(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_quote\n"));
   ell_parser_push_quote(); ;
}
YY_ACTION(void) yy_1_CLOSE(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_CLOSE\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_OPEN(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_OPEN\n"));
   ell_parser_push(); ;
}
YY_ACTION(void) yy_1_sym(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_sym\n"));
   ell_parser_add_sym(yytext); ;
}
YY_ACTION(void) yy_1_num(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_num\n"));
   ell_parser_add_num(yytext); ;
}
YY_ACTION(void) yy_1_str(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_str\n"));
   ell_parser_add_str(yytext); ;
}

YY_RULE(int) yy_eol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eol"));  if (!yymatchClass((unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_spc_char()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "spc_char"));
  {  int yypos3= yypos, yythunkpos3= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;  goto l3;
  l4:;	  yypos= yypos3; yythunkpos= yythunkpos3;  if (!yy_eol()) goto l2;
  }
  l3:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "spc_char", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "spc_char", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_contents()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "contents"));
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l7;  if (!yymatchClass((unsigned char *)"\377\377\377\377\357\377\377\377\377\377\377\377\377\377\377\337\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l7;
  l8:;	
  {  int yypos9= yypos, yythunkpos9= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\377\377\377\357\377\377\377\377\377\377\377\377\377\377\337\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l9;  goto l8;
  l9:;	  yypos= yypos9; yythunkpos= yythunkpos9;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l7;  yyDo(yy_1_contents, yybegin, yyend);  goto l6;
  l7:;	  yypos= yypos6; yythunkpos= yythunkpos6;  if (!yy_doc()) goto l5;
  }
  l6:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "contents", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "contents", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOSE()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOSE"));  if (!yymatchChar(')')) goto l10;  yyDo(yy_1_CLOSE, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE", yybuf+yypos));
  return 1;
  l10:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN"));  if (!yymatchChar('(')) goto l11;  yyDo(yy_1_OPEN, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN", yybuf+yypos));
  return 1;
  l11:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sym_char()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sym_char"));
  {  int yypos13= yypos, yythunkpos13= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\110\200\377\003\000\000\000\200\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;  goto l13;
  l14:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('-')) goto l15;  goto l13;
  l15:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('<')) goto l16;  goto l13;
  l16:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('>')) goto l17;  goto l13;
  l17:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('*')) goto l18;  goto l13;
  l18:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('+')) goto l12;
  }
  l13:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "sym_char", yybuf+yypos));
  return 1;
  l12:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sym_char", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_doc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "doc"));  if (!yymatchChar('$')) goto l19;  yyDo(yy_1_doc, yybegin, yyend);
  {  int yypos20= yypos, yythunkpos20= yythunkpos;  if (!yy_sym()) goto l20;  goto l21;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }
  l21:;	
  {  int yypos22= yypos, yythunkpos22= yythunkpos;  if (!yymatchChar('[')) goto l22;  if (!yy_exprs()) goto l22;  if (!yymatchChar(']')) goto l22;  goto l23;
  l22:;	  yypos= yypos22; yythunkpos= yythunkpos22;
  }
  l23:;	
  {  int yypos24= yypos, yythunkpos24= yythunkpos;  if (!yymatchChar('{')) goto l24;
  l26:;	
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_contents()) goto l27;  goto l26;
  l27:;	  yypos= yypos27; yythunkpos= yythunkpos27;
  }  if (!yymatchChar('}')) goto l24;  goto l25;
  l24:;	  yypos= yypos24; yythunkpos= yythunkpos24;
  }
  l25:;	  yyDo(yy_2_doc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "doc", yybuf+yypos));
  return 1;
  l19:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "doc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_lst()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "lst"));
  {  int yypos29= yypos, yythunkpos29= yythunkpos;  if (!yy_OPEN()) goto l30;  if (!yy_exprs()) goto l30;  if (!yy_CLOSE()) goto l30;  goto l29;
  l30:;	  yypos= yypos29; yythunkpos= yythunkpos29;  if (!yy_OPEN()) goto l28;
  {  int yypos31= yypos, yythunkpos31= yythunkpos;  if (!yy_spc()) goto l31;  goto l32;
  l31:;	  yypos= yypos31; yythunkpos= yythunkpos31;
  }
  l32:;	  if (!yy_CLOSE()) goto l28;
  }
  l29:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "lst", yybuf+yypos));
  return 1;
  l28:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "lst", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sym()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sym"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l33;  if (!yy_sym_char()) goto l33;
  l34:;	
  {  int yypos35= yypos, yythunkpos35= yythunkpos;  if (!yy_sym_char()) goto l35;  goto l34;
  l35:;	  yypos= yypos35; yythunkpos= yythunkpos35;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l33;  yyDo(yy_1_sym, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "sym", yybuf+yypos));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sym", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_num()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "num"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l36;
  {  int yypos37= yypos, yythunkpos37= yythunkpos;  if (!yymatchChar('-')) goto l37;  goto l38;
  l37:;	  yypos= yypos37; yythunkpos= yythunkpos37;
  }
  l38:;	  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l36;
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l36;  yyDo(yy_1_num, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "num", yybuf+yypos));
  return 1;
  l36:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "num", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_str()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "str"));  if (!yymatchChar('\"')) goto l41;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l41;
  l42:;	
  {  int yypos43= yypos, yythunkpos43= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l43;  goto l42;
  l43:;	  yypos= yypos43; yythunkpos= yythunkpos43;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l41;  if (!yymatchChar('\"')) goto l41;  yyDo(yy_1_str, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "str", yybuf+yypos));
  return 1;
  l41:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "str", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unsyntax_splicing()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unsyntax_splicing"));  if (!yymatchString(",@")) goto l44;  yyDo(yy_1_unsyntax_splicing, yybegin, yyend);  if (!yy_expr()) goto l44;  yyDo(yy_2_unsyntax_splicing, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unsyntax_splicing", yybuf+yypos));
  return 1;
  l44:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unsyntax_splicing", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unsyntax()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unsyntax"));  if (!yymatchChar(',')) goto l45;  yyDo(yy_1_unsyntax, yybegin, yyend);  if (!yy_expr()) goto l45;  yyDo(yy_2_unsyntax, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unsyntax", yybuf+yypos));
  return 1;
  l45:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unsyntax", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_quasisyntax()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "quasisyntax"));  if (!yymatchString("#`")) goto l46;  yyDo(yy_1_quasisyntax, yybegin, yyend);  if (!yy_expr()) goto l46;  yyDo(yy_2_quasisyntax, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "quasisyntax", yybuf+yypos));
  return 1;
  l46:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "quasisyntax", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_syntax()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "syntax"));  if (!yymatchString("#'")) goto l47;  yyDo(yy_1_syntax, yybegin, yyend);  if (!yy_expr()) goto l47;  yyDo(yy_2_syntax, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "syntax", yybuf+yypos));
  return 1;
  l47:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "syntax", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_quote()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "quote"));  if (!yymatchChar('\'')) goto l48;  yyDo(yy_1_quote, yybegin, yyend);  if (!yy_expr()) goto l48;  yyDo(yy_2_quote, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "quote", yybuf+yypos));
  return 1;
  l48:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "quote", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expr"));
  {  int yypos50= yypos, yythunkpos50= yythunkpos;  if (!yy_quote()) goto l51;  goto l50;
  l51:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_syntax()) goto l52;  goto l50;
  l52:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_quasisyntax()) goto l53;  goto l50;
  l53:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_unsyntax()) goto l54;  goto l50;
  l54:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_unsyntax_splicing()) goto l55;  goto l50;
  l55:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_str()) goto l56;  goto l50;
  l56:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_num()) goto l57;  goto l50;
  l57:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_sym()) goto l58;  goto l50;
  l58:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_lst()) goto l59;  goto l50;
  l59:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_doc()) goto l49;
  }
  l50:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yybuf+yypos));
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_spc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "spc"));  if (!yy_spc_char()) goto l60;
  l61:;	
  {  int yypos62= yypos, yythunkpos62= yythunkpos;  if (!yy_spc_char()) goto l62;  goto l61;
  l62:;	  yypos= yypos62; yythunkpos= yythunkpos62;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "spc", yybuf+yypos));
  return 1;
  l60:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "spc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos64= yypos, yythunkpos64= yythunkpos;  if (!yymatchDot()) goto l64;  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l63:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_exprs()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "exprs"));
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yy_spc()) goto l66;  goto l67;
  l66:;	  yypos= yypos66; yythunkpos= yythunkpos66;
  }
  l67:;	
  l68:;	
  {  int yypos69= yypos, yythunkpos69= yythunkpos;  if (!yy_expr()) goto l69;
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yy_spc()) goto l70;  goto l71;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }
  l71:;	  goto l68;
  l69:;	  yypos= yypos69; yythunkpos= yythunkpos69;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "exprs", yybuf+yypos));
  return 1;
  l65:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "exprs", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unit"));  if (!yy_exprs()) goto l72;  if (!yy_eof()) goto l72;
  yyprintf((stderr, "  ok   %s @ %s\n", "unit", yybuf+yypos));
  return 1;
  l72:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unit", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_unit);
}

#endif
