/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 21

void
ell_parser_add_sym(char *chars);
void
ell_parser_add_str(char *chars);
void
ell_parser_add_num(char *chars);
void
ell_parser_push();
void
ell_parser_pop();
void
ell_parser_push_special(struct ell_obj *sym);

#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_eol(); /* 21 */
YY_RULE(int) yy_spc_char(); /* 20 */
YY_RULE(int) yy_contents(); /* 19 */
YY_RULE(int) yy_CLOSE(); /* 18 */
YY_RULE(int) yy_OPEN(); /* 17 */
YY_RULE(int) yy_sym_char(); /* 16 */
YY_RULE(int) yy_doc(); /* 15 */
YY_RULE(int) yy_lst(); /* 14 */
YY_RULE(int) yy_sym(); /* 13 */
YY_RULE(int) yy_num(); /* 12 */
YY_RULE(int) yy_str(); /* 11 */
YY_RULE(int) yy_unsyntax_splicing(); /* 10 */
YY_RULE(int) yy_unsyntax(); /* 9 */
YY_RULE(int) yy_quasisyntax(); /* 8 */
YY_RULE(int) yy_syntax(); /* 7 */
YY_RULE(int) yy_quote(); /* 6 */
YY_RULE(int) yy_expr(); /* 5 */
YY_RULE(int) yy_spc(); /* 4 */
YY_RULE(int) yy_eof(); /* 3 */
YY_RULE(int) yy_exprs(); /* 2 */
YY_RULE(int) yy_unit(); /* 1 */

YY_ACTION(void) yy_1_contents(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_contents\n"));
   ell_parser_add_str(yytext); ;
}
YY_ACTION(void) yy_2_doc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_doc\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_doc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_doc\n"));
   ell_parser_push(); ;
}
YY_ACTION(void) yy_2_unsyntax_splicing(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_unsyntax_splicing\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_unsyntax_splicing(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unsyntax_splicing\n"));
   ell_parser_push_special(ELL_SYM(core_unsyntax_splicing)); ;
}
YY_ACTION(void) yy_2_unsyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_unsyntax\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_unsyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unsyntax\n"));
   ell_parser_push_special(ELL_SYM(core_unsyntax)); ;
}
YY_ACTION(void) yy_2_quasisyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_quasisyntax\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_quasisyntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_quasisyntax\n"));
   ell_parser_push_special(ELL_SYM(core_quasisyntax)); ;
}
YY_ACTION(void) yy_2_syntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_syntax\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_syntax(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_syntax\n"));
   ell_parser_push_special(ELL_SYM(core_syntax)); ;
}
YY_ACTION(void) yy_2_quote(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_quote\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_quote(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_quote\n"));
   ell_parser_push_special(ELL_SYM(core_quote)); ;
}
YY_ACTION(void) yy_1_CLOSE(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_CLOSE\n"));
   ell_parser_pop(); ;
}
YY_ACTION(void) yy_1_OPEN(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_OPEN\n"));
   ell_parser_push(); ;
}
YY_ACTION(void) yy_1_sym(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_sym\n"));
   ell_parser_add_sym(yytext); ;
}
YY_ACTION(void) yy_1_num(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_num\n"));
   ell_parser_add_num(yytext); ;
}
YY_ACTION(void) yy_1_str(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_str\n"));
   ell_parser_add_str(yytext); ;
}

YY_RULE(int) yy_eol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eol"));  if (!yymatchClass((unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_spc_char()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "spc_char"));
  {  int yypos3= yypos, yythunkpos3= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;  goto l3;
  l4:;	  yypos= yypos3; yythunkpos= yythunkpos3;  if (!yy_eol()) goto l2;
  }
  l3:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "spc_char", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "spc_char", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_contents()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "contents"));
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l7;  if (!yymatchClass((unsigned char *)"\377\377\377\377\357\377\377\377\377\377\377\377\377\377\377\337\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l7;
  l8:;	
  {  int yypos9= yypos, yythunkpos9= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\377\377\377\357\377\377\377\377\377\377\377\377\377\377\337\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l9;  goto l8;
  l9:;	  yypos= yypos9; yythunkpos= yythunkpos9;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l7;  yyDo(yy_1_contents, yybegin, yyend);  goto l6;
  l7:;	  yypos= yypos6; yythunkpos= yythunkpos6;  if (!yy_doc()) goto l5;
  }
  l6:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "contents", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "contents", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CLOSE()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOSE"));  if (!yymatchChar(')')) goto l10;  yyDo(yy_1_CLOSE, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE", yybuf+yypos));
  return 1;
  l10:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN"));  if (!yymatchChar('(')) goto l11;  yyDo(yy_1_OPEN, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN", yybuf+yypos));
  return 1;
  l11:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sym_char()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sym_char"));
  {  int yypos13= yypos, yythunkpos13= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\110\200\377\003\000\000\000\200\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;  goto l13;
  l14:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('-')) goto l15;  goto l13;
  l15:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('<')) goto l16;  goto l13;
  l16:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('>')) goto l17;  goto l13;
  l17:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('*')) goto l18;  goto l13;
  l18:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('+')) goto l19;  goto l13;
  l19:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar('?')) goto l12;
  }
  l13:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "sym_char", yybuf+yypos));
  return 1;
  l12:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sym_char", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_doc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "doc"));  if (!yymatchChar('$')) goto l20;  yyDo(yy_1_doc, yybegin, yyend);
  {  int yypos21= yypos, yythunkpos21= yythunkpos;  if (!yy_sym()) goto l21;  goto l22;
  l21:;	  yypos= yypos21; yythunkpos= yythunkpos21;
  }
  l22:;	
  {  int yypos23= yypos, yythunkpos23= yythunkpos;  if (!yymatchChar('[')) goto l23;  if (!yy_exprs()) goto l23;  if (!yymatchChar(']')) goto l23;  goto l24;
  l23:;	  yypos= yypos23; yythunkpos= yythunkpos23;
  }
  l24:;	
  {  int yypos25= yypos, yythunkpos25= yythunkpos;  if (!yymatchChar('{')) goto l25;
  l27:;	
  {  int yypos28= yypos, yythunkpos28= yythunkpos;  if (!yy_contents()) goto l28;  goto l27;
  l28:;	  yypos= yypos28; yythunkpos= yythunkpos28;
  }  if (!yymatchChar('}')) goto l25;  goto l26;
  l25:;	  yypos= yypos25; yythunkpos= yythunkpos25;
  }
  l26:;	  yyDo(yy_2_doc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "doc", yybuf+yypos));
  return 1;
  l20:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "doc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_lst()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "lst"));
  {  int yypos30= yypos, yythunkpos30= yythunkpos;  if (!yy_OPEN()) goto l31;  if (!yy_exprs()) goto l31;  if (!yy_CLOSE()) goto l31;  goto l30;
  l31:;	  yypos= yypos30; yythunkpos= yythunkpos30;  if (!yy_OPEN()) goto l29;
  {  int yypos32= yypos, yythunkpos32= yythunkpos;  if (!yy_spc()) goto l32;  goto l33;
  l32:;	  yypos= yypos32; yythunkpos= yythunkpos32;
  }
  l33:;	  if (!yy_CLOSE()) goto l29;
  }
  l30:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "lst", yybuf+yypos));
  return 1;
  l29:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "lst", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sym()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sym"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l34;  if (!yy_sym_char()) goto l34;
  l35:;	
  {  int yypos36= yypos, yythunkpos36= yythunkpos;  if (!yy_sym_char()) goto l36;  goto l35;
  l36:;	  yypos= yypos36; yythunkpos= yythunkpos36;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l34;  yyDo(yy_1_sym, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "sym", yybuf+yypos));
  return 1;
  l34:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sym", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_num()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "num"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l37;
  {  int yypos38= yypos, yythunkpos38= yythunkpos;  if (!yymatchChar('-')) goto l38;  goto l39;
  l38:;	  yypos= yypos38; yythunkpos= yythunkpos38;
  }
  l39:;	  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l37;
  l40:;	
  {  int yypos41= yypos, yythunkpos41= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l41;  goto l40;
  l41:;	  yypos= yypos41; yythunkpos= yythunkpos41;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l37;  yyDo(yy_1_num, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "num", yybuf+yypos));
  return 1;
  l37:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "num", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_str()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "str"));  if (!yymatchChar('\"')) goto l42;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l42;
  l43:;	
  {  int yypos44= yypos, yythunkpos44= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l44;  goto l43;
  l44:;	  yypos= yypos44; yythunkpos= yythunkpos44;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l42;  if (!yymatchChar('\"')) goto l42;  yyDo(yy_1_str, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "str", yybuf+yypos));
  return 1;
  l42:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "str", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unsyntax_splicing()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unsyntax_splicing"));  if (!yymatchString(",@")) goto l45;  yyDo(yy_1_unsyntax_splicing, yybegin, yyend);  if (!yy_expr()) goto l45;  yyDo(yy_2_unsyntax_splicing, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unsyntax_splicing", yybuf+yypos));
  return 1;
  l45:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unsyntax_splicing", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unsyntax()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unsyntax"));  if (!yymatchChar(',')) goto l46;  yyDo(yy_1_unsyntax, yybegin, yyend);  if (!yy_expr()) goto l46;  yyDo(yy_2_unsyntax, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unsyntax", yybuf+yypos));
  return 1;
  l46:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unsyntax", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_quasisyntax()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "quasisyntax"));  if (!yymatchString("#`")) goto l47;  yyDo(yy_1_quasisyntax, yybegin, yyend);  if (!yy_expr()) goto l47;  yyDo(yy_2_quasisyntax, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "quasisyntax", yybuf+yypos));
  return 1;
  l47:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "quasisyntax", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_syntax()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "syntax"));  if (!yymatchString("#'")) goto l48;  yyDo(yy_1_syntax, yybegin, yyend);  if (!yy_expr()) goto l48;  yyDo(yy_2_syntax, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "syntax", yybuf+yypos));
  return 1;
  l48:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "syntax", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_quote()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "quote"));  if (!yymatchChar('\'')) goto l49;  yyDo(yy_1_quote, yybegin, yyend);  if (!yy_expr()) goto l49;  yyDo(yy_2_quote, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "quote", yybuf+yypos));
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "quote", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expr"));
  {  int yypos51= yypos, yythunkpos51= yythunkpos;  if (!yy_quote()) goto l52;  goto l51;
  l52:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_syntax()) goto l53;  goto l51;
  l53:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_quasisyntax()) goto l54;  goto l51;
  l54:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_unsyntax()) goto l55;  goto l51;
  l55:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_unsyntax_splicing()) goto l56;  goto l51;
  l56:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_str()) goto l57;  goto l51;
  l57:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_num()) goto l58;  goto l51;
  l58:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_sym()) goto l59;  goto l51;
  l59:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_lst()) goto l60;  goto l51;
  l60:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_doc()) goto l50;
  }
  l51:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yybuf+yypos));
  return 1;
  l50:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_spc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "spc"));  if (!yy_spc_char()) goto l61;
  l62:;	
  {  int yypos63= yypos, yythunkpos63= yythunkpos;  if (!yy_spc_char()) goto l63;  goto l62;
  l63:;	  yypos= yypos63; yythunkpos= yythunkpos63;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "spc", yybuf+yypos));
  return 1;
  l61:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "spc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos65= yypos, yythunkpos65= yythunkpos;  if (!yymatchDot()) goto l65;  goto l64;
  l65:;	  yypos= yypos65; yythunkpos= yythunkpos65;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l64:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_exprs()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "exprs"));
  {  int yypos67= yypos, yythunkpos67= yythunkpos;  if (!yy_spc()) goto l67;  goto l68;
  l67:;	  yypos= yypos67; yythunkpos= yythunkpos67;
  }
  l68:;	
  l69:;	
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yy_expr()) goto l70;
  {  int yypos71= yypos, yythunkpos71= yythunkpos;  if (!yy_spc()) goto l71;  goto l72;
  l71:;	  yypos= yypos71; yythunkpos= yythunkpos71;
  }
  l72:;	  goto l69;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "exprs", yybuf+yypos));
  return 1;
  l66:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "exprs", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unit"));  if (!yy_exprs()) goto l73;  if (!yy_eof()) goto l73;
  yyprintf((stderr, "  ok   %s @ %s\n", "unit", yybuf+yypos));
  return 1;
  l73:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unit", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_unit);
}

#endif
