ELL_DEFSYM(add, "add")
ELL_DEFSYM(first, "first")
ELL_DEFSYM(second, "second")
ELL_DEFSYM(third, "third")
ELL_DEFSYM(fourth, "fourth")
ELL_DEFSYM(print_object, "print-object")

ELL_DEFSYM(core_fref, "ell-fref")
ELL_DEFSYM(core_def,  "ell-def")
ELL_DEFSYM(core_fdef, "ell-fdef")
ELL_DEFSYM(core_set,  "ell-set")
ELL_DEFSYM(core_fset, "ell-fset")
ELL_DEFSYM(core_cond, "ell-cond")
ELL_DEFSYM(core_seq,  "ell-seq")
ELL_DEFSYM(core_lam,  "ell-lam")
ELL_DEFSYM(core_app,  "ell-app")
ELL_DEFSYM(core_mdef, "ell-mdef")

ELL_DEFSYM(core_syntax, "syntax")
ELL_DEFSYM(core_quasisyntax, "quasisyntax")
ELL_DEFSYM(core_unsyntax, "unsyntax")
ELL_DEFSYM(core_unsyntax_splicing, "unsyntax-splicing")
ELL_DEFSYM(core_syntax_list, "syntax-list")
ELL_DEFSYM(core_append_syntax_lists, "append-syntax-lists")

ELL_DEFSYM(param_optional, "&optional")
ELL_DEFSYM(param_key, "&key")
ELL_DEFSYM(param_rest, "&rest")
ELL_DEFSYM(param_all_keys, "&all-keys")
